version: 0.1
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=practice -Dsonar.organization=projectOrg -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=a38f8e6a7e9e96e478e4bd0fe6e1234beeb788cc 
- name: TruffleHog OSS
  uses: trufflesecurity/trufflehog@v3.88.2
